<?php

namespace App\Http\Controllers\Api\Iot;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;

/**
 * TEMPORARY — simulates an S3 PUT-to-presigned-URL upload on local disk.
 * Only reachable via a signed URL generated by LocalMediaUploadMockService.
 * Deleted along with that service once S3 is live.
 */
class IotLocalMediaMockController extends Controller
{
    public function receive(Request $request, string $key): Response
    {
        if (! $request->hasValidSignature()) {
            abort(403, 'Invalid or expired upload URL.');
        }

        $objectKey = base64_decode($key);

        Storage::disk('local_iot_mock')->put($objectKey, $request->getContent());

        return response()->noContent();
    }
}